language: python
python:
  - "3.8"
env:
  jobs:
    - TRAVIS_PULL_REQUEST=false
branches:
  only:
    - master
install: pip3 install -r requirements.txt
script: python3 -m py.test --cov ./pytest_html_reporter/ tests/unit/
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)